# Generated by Django 5.1.4 on 2025-01-18 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, verbose_name="Nom d'utilisateur")),
                ('request_url', models.JSONField(verbose_name='Requete Url')),
                ('request_method', models.CharField(max_length=255, verbose_name='Requete Methode')),
                ('is_denied', models.BooleanField(default=False, verbose_name='Is denied')),
                ('denial_reason', models.CharField(max_length=255, verbose_name='Denial Reason')),
                ('auth_method', models.CharField(max_length=255, verbose_name='auht Method')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='Adresse IP')),
                ('last_access_date', models.DateTimeField(null=True, verbose_name="Dernière date d'accès")),
                ('user_agent', models.JSONField(null=True, verbose_name='Agent utilisateur')),
                ('application_id', models.CharField(max_length=255, verbose_name='Application ID')),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True, verbose_name='Token JWT')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, verbose_name="Nom d'utilisateur")),
                ('is_active', models.BooleanField(default=False, verbose_name='Validité')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='Adresse IP')),
                ('last_access_date', models.DateTimeField(null=True, verbose_name="Dernière date d'accès")),
                ('user_agent', models.JSONField(null=True, verbose_name='Agent utilisateur')),
                ('user_data', models.JSONField(verbose_name="Données de l'utilisateur")),
                ('application_id', models.CharField(max_length=255, verbose_name='Application ID')),
                ('logout_at', models.DateTimeField(null=True, verbose_name='Date de déconnexion')),
                ('auth_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_users', to='custom_auth.authlog', verbose_name='Auth log user')),
                ('logout_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logout_users', to='custom_auth.authuser', verbose_name='Déconnecté par')),
            ],
        ),
    ]
