# Generated by Django 5.1.4 on 2025-01-18 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_users', to='user.role', verbose_name="Role d'un utilisateur front office"),
        ),
        migrations.AddField(
            model_name='authlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_core_entities', to='custom_auth.authuser', verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='authlog',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_core_entities', to='custom_auth.authuser', verbose_name='Supprimé par'),
        ),
        migrations.AddField(
            model_name='authlog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_core_entities', to='custom_auth.authuser', verbose_name='Mis à jour par'),
        ),
    ]
