# Generated by Django 5.1.4 on 2025-01-20 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
