# Generated by Django 5.1.4 on 2025-01-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_alter_authuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
