# Generated by Django 5.1.4 on 2025-01-21 00:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_access',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
